import type { Metadata } from "next";
import { Roboto } from "next/font/google";

/* Web3Modal */
import { Web3Modal } from "@/app/utils/context/web3modal";

/* Stylesheet */
import "./theme/globals.scss";

const roboto = Roboto({
    weight: ["300", "400", "500"],
    subsets: ["latin"]
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={roboto.className}
                suppressHydrationWarning={true}
            >
                <Web3Modal>{children}</Web3Modal>
            </body>
        </html>
    );
}
