import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Web3Modal } from "@/app/utils/context/web3modal";

/* Stylesheet */
import "./theme/globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={inter.className}
                suppressHydrationWarning={true}
            >
                <Web3Modal>{children}</Web3Modal>
            </body>
        </html>
    );
}
